# Generated by Django 5.0.1 on 2024-05-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
    ]
